INSERT INTO PERSON(FIRST_NAME, LAST_NAME, AGE, PESEL, PASSWORD) VALUES ('Ania','Nowak', 20, '51101069339','$2a$12$Y3grN5uQ8jrSsNEj28NBgO2DhDJ4yCcNsLMQz0Z6wAdsoP3iDms/G');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, AGE, PESEL, PASSWORD) VALUES ('Monika','Kowalska', 25, '78052493291','$2a$12$n6APc5tEN/lT3IawuYpspuq.M4stx6bryCKc7h3mdK/MxdHV/kIIO');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, AGE, PESEL, PASSWORD) VALUES ('Kasia','Matecka', 20, '62122375183','$2a$12$Y3grN5uQ8jrSsNEj28NBgO2DhDJ4yCcNsLMQz0Z6wAdsoP3iDms/G');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, AGE, PESEL, PASSWORD) VALUES ('Florentyn','Kowalski', 25, '55060486745','$2a$12$n6APc5tEN/lT3IawuYpspuq.M4stx6bryCKc7h3mdK/MxdHV/kIIO');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, AGE, PESEL, PASSWORD) VALUES ('Admin','Kowalski', 25, '34060486745','$2a$12$n6APc5tEN/lT3IawuYpspuq.M4stx6bryCKc7h3mdK/MxdHV/kIIO');
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, AGE, PESEL, PASSWORD) VALUES ('Piotr','Adamski', 22, '54090156376','12345'); --tymi sie nie zalogujemy, musza byc zakodowane hasla na bazie danych
INSERT INTO PERSON(FIRST_NAME, LAST_NAME, AGE, PESEL, PASSWORD) VALUES ('Jacek','Nowik', 30, '77032484399','12345'); --tymi sie nie zalogujemy, musza byc zakodowane hasla na bazie danych

INSERT INTO ACCOUNT(ID, ACCOUNT_NUMBER, BALANCE, PERSON_ID) VALUES (1000, '100020003000', 1000, 1);
INSERT INTO ACCOUNT(ID, ACCOUNT_NUMBER, BALANCE, PERSON_ID) VALUES (2000, '210030005000', 2000, 2);

INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_CREATOR');
INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_READER');
INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_UPDATER');
INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_REMOVER');

INSERT INTO AUTHORITY(AUTHORITY_NAME) VALUES ('ROLE_ADMIN');


INSERT INTO PERSON_AUTHORITIES VALUES(1,1);
INSERT INTO PERSON_AUTHORITIES VALUES(2,2);
INSERT INTO PERSON_AUTHORITIES VALUES(3,3);
INSERT INTO PERSON_AUTHORITIES VALUES(4,4);

-- INSERT INTO PERSON_AUTHORITIES VALUES(5,1);
-- INSERT INTO PERSON_AUTHORITIES VALUES(5,2);
-- INSERT INTO PERSON_AUTHORITIES VALUES(5,3);
-- INSERT INTO PERSON_AUTHORITIES VALUES(5,4);

INSERT INTO PERSON_AUTHORITIES VALUES(5,5);
